adx_contentdisposition: 756150000
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: Product image 1.png
adx_parentpageid: e1acc288-92f1-4695-8aa5-7c4dc439f6bb
adx_partialurl: Product image 1.png
adx_publishingstateid: 1363c145-fb5a-4fe8-aef1-6c9197cb44ed
adx_webfileid: ce82b6ad-101f-4189-985d-8eaea9db0498
annotationid: ba5e3510-397f-ee11-8179-0022482d6c81
filename: Product image 1.png
isdocument: true
mimetype: image/png
objectid: ce82b6ad-101f-4189-985d-8eaea9db0498
objecttypecode: adx_webfile
