adx_createdOn: 2024-01-16T07:52:16.0960000Z
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: product-2.jpg
adx_parentpageid: e740e969-cb91-4888-81ed-1a289bc99048
adx_partialurl: product-2.jpg
adx_publishingstateid: 223b296f-4977-4774-924c-19e26a31cacc
adx_summary: ''
adx_title: ''
adx_webfileid: 90d3c867-a55a-4c3c-a43c-8500b72c7cc5
annotationid: 0a9f8229-44b4-ee11-a569-0022482d6c81
filename: product-2.jpg
isdocument: true
mimetype: image/jpeg
objectid: 90d3c867-a55a-4c3c-a43c-8500b72c7cc5
objecttypecode: adx_webfile
