adx_createdOn: 2024-01-16T07:52:30.5990000Z
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: product-3.jpg
adx_parentpageid: e740e969-cb91-4888-81ed-1a289bc99048
adx_partialurl: product-3.jpg
adx_publishingstateid: 223b296f-4977-4774-924c-19e26a31cacc
adx_summary: ''
adx_title: ''
adx_webfileid: 7013bad7-2dbb-4c8f-b346-3f1d6f219472
annotationid: d33e8f33-44b4-ee11-a569-0022482d6c81
filename: product-3.jpg
isdocument: true
mimetype: image/jpeg
objectid: 7013bad7-2dbb-4c8f-b346-3f1d6f219472
objecttypecode: adx_webfile
