adx_createdOn: 2024-01-16T07:51:59.3430000Z
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: product-1.jpg
adx_parentpageid: e740e969-cb91-4888-81ed-1a289bc99048
adx_partialurl: product-1.jpg
adx_publishingstateid: 223b296f-4977-4774-924c-19e26a31cacc
adx_summary: ''
adx_title: ''
adx_webfileid: e3e3d0d2-5fc7-453e-9370-24d9fe70e2de
annotationid: e99eab20-44b4-ee11-a569-0022482d6c81
filename: product-1.jpg
isdocument: true
mimetype: image/jpeg
objectid: e3e3d0d2-5fc7-453e-9370-24d9fe70e2de
objecttypecode: adx_webfile
